#!/usr/bin/env bash

prj_root=`dirname $(realpath "$0")`/..
tgt_dir=$prj_root/target
bin_dir=$tgt_dir/bin

lib_compart_dir=$prj_root/libcompart_shohola
hello_dir=$lib_compart_dir/hello_compartment
hello_exe=$bin_dir/hello_compartment

life_dir=$prj_root/life
life_exe=$bin_dir/life
prof_life_exe=$bin_dir/gprof_life
part_exe=$bin_dir/partitioned_life

report_dir=$prj_root/report

args=" -s 3 -c 5 -i 011001010"
# args="-s 20 -c 100 -i 011001010110101111011001010110101111010111101010101111100110111"

# build
echo "Building life binaries..."
echo ""
sudo -u andrew make clean && sudo -u andrew make part && $part_exe $args
echo ""
echo "done."
echo ""
